//! Round-trip every scalar enum value listed on OANDA's definition pages.
#![allow(clippy::expect_used, clippy::unwrap_used, clippy::panic)]
use oanda_client::models;
use serde::{Serialize, de::DeserializeOwned};
use std::fmt::Debug;
fn round_trip<T: Serialize + DeserializeOwned + Debug>(wire: &str) {
    let decoded: T = serde_json::from_value(serde_json::Value::String(wire.to_owned()))
        .expect("decode documented enum");
    let encoded = serde_json::to_value(decoded).expect("encode documented enum");
    assert_eq!(encoded, serde_json::Value::String(wire.to_owned()));
}
#[test]
fn all_documented_scalar_enum_variants_round_trip() {
    round_trip::<models::GuaranteedStopLossOrderMode>("DISABLED");
    round_trip::<models::GuaranteedStopLossOrderMode>("ALLOWED");
    round_trip::<models::GuaranteedStopLossOrderMode>("REQUIRED");
    round_trip::<models::GuaranteedStopLossOrderMutability>("FIXED");
    round_trip::<models::GuaranteedStopLossOrderMutability>("REPLACEABLE");
    round_trip::<models::GuaranteedStopLossOrderMutability>("CANCELABLE");
    round_trip::<models::GuaranteedStopLossOrderMutability>("PRICE_WIDEN_ONLY");
    round_trip::<models::AccountFinancingMode>("NO_FINANCING");
    round_trip::<models::AccountFinancingMode>("SECOND_BY_SECOND");
    round_trip::<models::AccountFinancingMode>("DAILY");
    round_trip::<models::PositionAggregationMode>("ABSOLUTE_SUM");
    round_trip::<models::PositionAggregationMode>("MAXIMAL_SIDE");
    round_trip::<models::PositionAggregationMode>("NET_SUM");
    round_trip::<models::CandlestickGranularity>("S5");
    round_trip::<models::CandlestickGranularity>("S10");
    round_trip::<models::CandlestickGranularity>("S15");
    round_trip::<models::CandlestickGranularity>("S30");
    round_trip::<models::CandlestickGranularity>("M1");
    round_trip::<models::CandlestickGranularity>("M2");
    round_trip::<models::CandlestickGranularity>("M4");
    round_trip::<models::CandlestickGranularity>("M5");
    round_trip::<models::CandlestickGranularity>("M10");
    round_trip::<models::CandlestickGranularity>("M15");
    round_trip::<models::CandlestickGranularity>("M30");
    round_trip::<models::CandlestickGranularity>("H1");
    round_trip::<models::CandlestickGranularity>("H2");
    round_trip::<models::CandlestickGranularity>("H3");
    round_trip::<models::CandlestickGranularity>("H4");
    round_trip::<models::CandlestickGranularity>("H6");
    round_trip::<models::CandlestickGranularity>("H8");
    round_trip::<models::CandlestickGranularity>("H12");
    round_trip::<models::CandlestickGranularity>("D");
    round_trip::<models::CandlestickGranularity>("W");
    round_trip::<models::CandlestickGranularity>("M");
    round_trip::<models::WeeklyAlignment>("Monday");
    round_trip::<models::WeeklyAlignment>("Tuesday");
    round_trip::<models::WeeklyAlignment>("Wednesday");
    round_trip::<models::WeeklyAlignment>("Thursday");
    round_trip::<models::WeeklyAlignment>("Friday");
    round_trip::<models::WeeklyAlignment>("Saturday");
    round_trip::<models::WeeklyAlignment>("Sunday");
    round_trip::<models::OrderType>("MARKET");
    round_trip::<models::OrderType>("LIMIT");
    round_trip::<models::OrderType>("STOP");
    round_trip::<models::OrderType>("MARKET_IF_TOUCHED");
    round_trip::<models::OrderType>("TAKE_PROFIT");
    round_trip::<models::OrderType>("STOP_LOSS");
    round_trip::<models::OrderType>("GUARANTEED_STOP_LOSS");
    round_trip::<models::OrderType>("TRAILING_STOP_LOSS");
    round_trip::<models::OrderType>("FIXED_PRICE");
    round_trip::<models::CancellableOrderType>("LIMIT");
    round_trip::<models::CancellableOrderType>("STOP");
    round_trip::<models::CancellableOrderType>("MARKET_IF_TOUCHED");
    round_trip::<models::CancellableOrderType>("TAKE_PROFIT");
    round_trip::<models::CancellableOrderType>("STOP_LOSS");
    round_trip::<models::CancellableOrderType>("GUARANTEED_STOP_LOSS");
    round_trip::<models::CancellableOrderType>("TRAILING_STOP_LOSS");
    round_trip::<models::OrderState>("PENDING");
    round_trip::<models::OrderState>("FILLED");
    round_trip::<models::OrderState>("TRIGGERED");
    round_trip::<models::OrderState>("CANCELLED");
    round_trip::<models::OrderStateFilter>("PENDING");
    round_trip::<models::OrderStateFilter>("FILLED");
    round_trip::<models::OrderStateFilter>("TRIGGERED");
    round_trip::<models::OrderStateFilter>("CANCELLED");
    round_trip::<models::OrderStateFilter>("ALL");
    round_trip::<models::TimeInForce>("GTC");
    round_trip::<models::TimeInForce>("GTD");
    round_trip::<models::TimeInForce>("GFD");
    round_trip::<models::TimeInForce>("FOK");
    round_trip::<models::TimeInForce>("IOC");
    round_trip::<models::OrderPositionFill>("OPEN_ONLY");
    round_trip::<models::OrderPositionFill>("REDUCE_FIRST");
    round_trip::<models::OrderPositionFill>("REDUCE_ONLY");
    round_trip::<models::OrderPositionFill>("DEFAULT");
    round_trip::<models::OrderTriggerCondition>("DEFAULT");
    round_trip::<models::OrderTriggerCondition>("INVERSE");
    round_trip::<models::OrderTriggerCondition>("BID");
    round_trip::<models::OrderTriggerCondition>("ASK");
    round_trip::<models::OrderTriggerCondition>("MID");
    round_trip::<models::TradeState>("OPEN");
    round_trip::<models::TradeState>("CLOSED");
    round_trip::<models::TradeState>("CLOSE_WHEN_TRADEABLE");
    round_trip::<models::TradeStateFilter>("OPEN");
    round_trip::<models::TradeStateFilter>("CLOSED");
    round_trip::<models::TradeStateFilter>("CLOSE_WHEN_TRADEABLE");
    round_trip::<models::TradeStateFilter>("ALL");
    round_trip::<models::TradePL>("POSITIVE");
    round_trip::<models::TradePL>("NEGATIVE");
    round_trip::<models::TradePL>("ZERO");
    round_trip::<models::TransactionType>("CREATE");
    round_trip::<models::TransactionType>("CLOSE");
    round_trip::<models::TransactionType>("REOPEN");
    round_trip::<models::TransactionType>("CLIENT_CONFIGURE");
    round_trip::<models::TransactionType>("CLIENT_CONFIGURE_REJECT");
    round_trip::<models::TransactionType>("TRANSFER_FUNDS");
    round_trip::<models::TransactionType>("TRANSFER_FUNDS_REJECT");
    round_trip::<models::TransactionType>("MARKET_ORDER");
    round_trip::<models::TransactionType>("MARKET_ORDER_REJECT");
    round_trip::<models::TransactionType>("FIXED_PRICE_ORDER");
    round_trip::<models::TransactionType>("LIMIT_ORDER");
    round_trip::<models::TransactionType>("LIMIT_ORDER_REJECT");
    round_trip::<models::TransactionType>("STOP_ORDER");
    round_trip::<models::TransactionType>("STOP_ORDER_REJECT");
    round_trip::<models::TransactionType>("MARKET_IF_TOUCHED_ORDER");
    round_trip::<models::TransactionType>("MARKET_IF_TOUCHED_ORDER_REJECT");
    round_trip::<models::TransactionType>("TAKE_PROFIT_ORDER");
    round_trip::<models::TransactionType>("TAKE_PROFIT_ORDER_REJECT");
    round_trip::<models::TransactionType>("STOP_LOSS_ORDER");
    round_trip::<models::TransactionType>("STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionType>("GUARANTEED_STOP_LOSS_ORDER");
    round_trip::<models::TransactionType>("GUARANTEED_STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionType>("TRAILING_STOP_LOSS_ORDER");
    round_trip::<models::TransactionType>("TRAILING_STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionType>("ORDER_FILL");
    round_trip::<models::TransactionType>("ORDER_CANCEL");
    round_trip::<models::TransactionType>("ORDER_CANCEL_REJECT");
    round_trip::<models::TransactionType>("ORDER_CLIENT_EXTENSIONS_MODIFY");
    round_trip::<models::TransactionType>("ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT");
    round_trip::<models::TransactionType>("TRADE_CLIENT_EXTENSIONS_MODIFY");
    round_trip::<models::TransactionType>("TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT");
    round_trip::<models::TransactionType>("MARGIN_CALL_ENTER");
    round_trip::<models::TransactionType>("MARGIN_CALL_EXTEND");
    round_trip::<models::TransactionType>("MARGIN_CALL_EXIT");
    round_trip::<models::TransactionType>("DELAYED_TRADE_CLOSURE");
    round_trip::<models::TransactionType>("DAILY_FINANCING");
    round_trip::<models::TransactionType>("DIVIDEND_ADJUSTMENT");
    round_trip::<models::TransactionType>("RESET_RESETTABLE_PL");
    round_trip::<models::FundingReason>("CLIENT_FUNDING");
    round_trip::<models::FundingReason>("ACCOUNT_TRANSFER");
    round_trip::<models::FundingReason>("DIVISION_MIGRATION");
    round_trip::<models::FundingReason>("SITE_MIGRATION");
    round_trip::<models::FundingReason>("ADJUSTMENT");
    round_trip::<models::MarketOrderReason>("CLIENT_ORDER");
    round_trip::<models::MarketOrderReason>("TRADE_CLOSE");
    round_trip::<models::MarketOrderReason>("POSITION_CLOSEOUT");
    round_trip::<models::MarketOrderReason>("MARGIN_CLOSEOUT");
    round_trip::<models::MarketOrderReason>("DELAYED_TRADE_CLOSE");
    round_trip::<models::FixedPriceOrderReason>("PLATFORM_ACCOUNT_MIGRATION");
    round_trip::<models::FixedPriceOrderReason>("TRADE_CLOSE_DIVISION_ACCOUNT_MIGRATION");
    round_trip::<models::FixedPriceOrderReason>("TRADE_CLOSE_ADMINISTRATIVE_ACTION");
    round_trip::<models::LimitOrderReason>("CLIENT_ORDER");
    round_trip::<models::LimitOrderReason>("REPLACEMENT");
    round_trip::<models::StopOrderReason>("CLIENT_ORDER");
    round_trip::<models::StopOrderReason>("REPLACEMENT");
    round_trip::<models::MarketIfTouchedOrderReason>("CLIENT_ORDER");
    round_trip::<models::MarketIfTouchedOrderReason>("REPLACEMENT");
    round_trip::<models::TakeProfitOrderReason>("CLIENT_ORDER");
    round_trip::<models::TakeProfitOrderReason>("REPLACEMENT");
    round_trip::<models::TakeProfitOrderReason>("ON_FILL");
    round_trip::<models::StopLossOrderReason>("CLIENT_ORDER");
    round_trip::<models::StopLossOrderReason>("REPLACEMENT");
    round_trip::<models::StopLossOrderReason>("ON_FILL");
    round_trip::<models::GuaranteedStopLossOrderReason>("CLIENT_ORDER");
    round_trip::<models::GuaranteedStopLossOrderReason>("REPLACEMENT");
    round_trip::<models::GuaranteedStopLossOrderReason>("ON_FILL");
    round_trip::<models::TrailingStopLossOrderReason>("CLIENT_ORDER");
    round_trip::<models::TrailingStopLossOrderReason>("REPLACEMENT");
    round_trip::<models::TrailingStopLossOrderReason>("ON_FILL");
    round_trip::<models::OrderFillReason>("LIMIT_ORDER");
    round_trip::<models::OrderFillReason>("STOP_ORDER");
    round_trip::<models::OrderFillReason>("MARKET_IF_TOUCHED_ORDER");
    round_trip::<models::OrderFillReason>("TAKE_PROFIT_ORDER");
    round_trip::<models::OrderFillReason>("STOP_LOSS_ORDER");
    round_trip::<models::OrderFillReason>("GUARANTEED_STOP_LOSS_ORDER");
    round_trip::<models::OrderFillReason>("TRAILING_STOP_LOSS_ORDER");
    round_trip::<models::OrderFillReason>("MARKET_ORDER");
    round_trip::<models::OrderFillReason>("MARKET_ORDER_TRADE_CLOSE");
    round_trip::<models::OrderFillReason>("MARKET_ORDER_POSITION_CLOSEOUT");
    round_trip::<models::OrderFillReason>("MARKET_ORDER_MARGIN_CLOSEOUT");
    round_trip::<models::OrderFillReason>("MARKET_ORDER_DELAYED_TRADE_CLOSE");
    round_trip::<models::OrderFillReason>("FIXED_PRICE_ORDER");
    round_trip::<models::OrderFillReason>("FIXED_PRICE_ORDER_PLATFORM_ACCOUNT_MIGRATION");
    round_trip::<models::OrderFillReason>("FIXED_PRICE_ORDER_DIVISION_ACCOUNT_MIGRATION");
    round_trip::<models::OrderFillReason>("FIXED_PRICE_ORDER_ADMINISTRATIVE_ACTION");
    round_trip::<models::OrderCancelReason>("INTERNAL_SERVER_ERROR");
    round_trip::<models::OrderCancelReason>("ACCOUNT_LOCKED");
    round_trip::<models::OrderCancelReason>("ACCOUNT_NEW_POSITIONS_LOCKED");
    round_trip::<models::OrderCancelReason>("ACCOUNT_ORDER_CREATION_LOCKED");
    round_trip::<models::OrderCancelReason>("ACCOUNT_ORDER_FILL_LOCKED");
    round_trip::<models::OrderCancelReason>("CLIENT_REQUEST");
    round_trip::<models::OrderCancelReason>("MIGRATION");
    round_trip::<models::OrderCancelReason>("MARKET_HALTED");
    round_trip::<models::OrderCancelReason>("LINKED_TRADE_CLOSED");
    round_trip::<models::OrderCancelReason>("TIME_IN_FORCE_EXPIRED");
    round_trip::<models::OrderCancelReason>("INSUFFICIENT_MARGIN");
    round_trip::<models::OrderCancelReason>("FIFO_VIOLATION");
    round_trip::<models::OrderCancelReason>("BOUNDS_VIOLATION");
    round_trip::<models::OrderCancelReason>("CLIENT_REQUEST_REPLACED");
    round_trip::<models::OrderCancelReason>("DIVIDEND_ADJUSTMENT_REPLACED");
    round_trip::<models::OrderCancelReason>("INSUFFICIENT_LIQUIDITY");
    round_trip::<models::OrderCancelReason>("TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::OrderCancelReason>("TAKE_PROFIT_ON_FILL_LOSS");
    round_trip::<models::OrderCancelReason>("LOSING_TAKE_PROFIT");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_LOSS");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_REQUIRED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED");
    round_trip::<models::OrderCancelReason>(
        "STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::OrderCancelReason>(
        "STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED",
    );
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GUARANTEED_HEDGING_NOT_ALLOWED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_LOSS");
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED",
    );
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED");
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED",
    );
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED",
    );
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_HEDGING_NOT_ALLOWED");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID");
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID",
    );
    round_trip::<models::OrderCancelReason>("TAKE_PROFIT_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED");
    round_trip::<models::OrderCancelReason>("TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::OrderCancelReason>("CLIENT_TRADE_ID_ALREADY_EXISTS");
    round_trip::<models::OrderCancelReason>("POSITION_CLOSEOUT_FAILED");
    round_trip::<models::OrderCancelReason>("OPEN_TRADES_ALLOWED_EXCEEDED");
    round_trip::<models::OrderCancelReason>("PENDING_ORDERS_ALLOWED_EXCEEDED");
    round_trip::<models::OrderCancelReason>("TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS");
    round_trip::<models::OrderCancelReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS",
    );
    round_trip::<models::OrderCancelReason>(
        "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_ALREADY_EXISTS",
    );
    round_trip::<models::OrderCancelReason>("POSITION_SIZE_EXCEEDED");
    round_trip::<models::OrderCancelReason>("HEDGING_GSLO_VIOLATION");
    round_trip::<models::OrderCancelReason>("ACCOUNT_POSITION_VALUE_LIMIT_EXCEEDED");
    round_trip::<models::OrderCancelReason>("INSTRUMENT_BID_REDUCE_ONLY");
    round_trip::<models::OrderCancelReason>("INSTRUMENT_ASK_REDUCE_ONLY");
    round_trip::<models::OrderCancelReason>("INSTRUMENT_BID_HALTED");
    round_trip::<models::OrderCancelReason>("INSTRUMENT_ASK_HALTED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GUARANTEED_BID_HALTED");
    round_trip::<models::OrderCancelReason>("STOP_LOSS_ON_FILL_GUARANTEED_ASK_HALTED");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_BID_HALTED");
    round_trip::<models::OrderCancelReason>("GUARANTEED_STOP_LOSS_ON_FILL_ASK_HALTED");
    round_trip::<models::OrderCancelReason>("FIFO_VIOLATION_SAFEGUARD_VIOLATION");
    round_trip::<models::OrderCancelReason>("FIFO_VIOLATION_SAFEGUARD_PARTIAL_CLOSE_VIOLATION");
    round_trip::<models::OrderCancelReason>(
        "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION",
    );
    round_trip::<models::MarketOrderMarginCloseoutReason>("MARGIN_CHECK_VIOLATION");
    round_trip::<models::MarketOrderMarginCloseoutReason>("REGULATORY_MARGIN_CALL_VIOLATION");
    round_trip::<models::MarketOrderMarginCloseoutReason>("REGULATORY_MARGIN_CHECK_VIOLATION");
    round_trip::<models::TransactionRejectReason>("INTERNAL_SERVER_ERROR");
    round_trip::<models::TransactionRejectReason>("INSTRUMENT_PRICE_UNKNOWN");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_NOT_ACTIVE");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_LOCKED");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_ORDER_CREATION_LOCKED");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_CONFIGURATION_LOCKED");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_DEPOSIT_LOCKED");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_WITHDRAWAL_LOCKED");
    round_trip::<models::TransactionRejectReason>("ACCOUNT_ORDER_CANCEL_LOCKED");
    round_trip::<models::TransactionRejectReason>("INSTRUMENT_NOT_TRADEABLE");
    round_trip::<models::TransactionRejectReason>("PENDING_ORDERS_ALLOWED_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("ORDER_ID_UNSPECIFIED");
    round_trip::<models::TransactionRejectReason>("ORDER_DOESNT_EXIST");
    round_trip::<models::TransactionRejectReason>("ORDER_IDENTIFIER_INCONSISTENCY");
    round_trip::<models::TransactionRejectReason>("TRADE_ID_UNSPECIFIED");
    round_trip::<models::TransactionRejectReason>("TRADE_DOESNT_EXIST");
    round_trip::<models::TransactionRejectReason>("TRADE_IDENTIFIER_INCONSISTENCY");
    round_trip::<models::TransactionRejectReason>("INSUFFICIENT_MARGIN");
    round_trip::<models::TransactionRejectReason>("INSTRUMENT_MISSING");
    round_trip::<models::TransactionRejectReason>("INSTRUMENT_UNKNOWN");
    round_trip::<models::TransactionRejectReason>("UNITS_MISSING");
    round_trip::<models::TransactionRejectReason>("UNITS_INVALID");
    round_trip::<models::TransactionRejectReason>("UNITS_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("UNITS_LIMIT_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("UNITS_MINIMUM_NOT_MET");
    round_trip::<models::TransactionRejectReason>("PRICE_MISSING");
    round_trip::<models::TransactionRejectReason>("PRICE_INVALID");
    round_trip::<models::TransactionRejectReason>("PRICE_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("PRICE_DISTANCE_MISSING");
    round_trip::<models::TransactionRejectReason>("PRICE_DISTANCE_INVALID");
    round_trip::<models::TransactionRejectReason>("PRICE_DISTANCE_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("PRICE_DISTANCE_MAXIMUM_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("PRICE_DISTANCE_MINIMUM_NOT_MET");
    round_trip::<models::TransactionRejectReason>("TIME_IN_FORCE_MISSING");
    round_trip::<models::TransactionRejectReason>("TIME_IN_FORCE_INVALID");
    round_trip::<models::TransactionRejectReason>("TIME_IN_FORCE_GTD_TIMESTAMP_MISSING");
    round_trip::<models::TransactionRejectReason>("TIME_IN_FORCE_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::TransactionRejectReason>("PRICE_BOUND_INVALID");
    round_trip::<models::TransactionRejectReason>("PRICE_BOUND_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("ORDERS_ON_FILL_DUPLICATE_CLIENT_ORDER_IDS");
    round_trip::<models::TransactionRejectReason>("TRADE_ON_FILL_CLIENT_EXTENSIONS_NOT_SUPPORTED");
    round_trip::<models::TransactionRejectReason>("CLIENT_ORDER_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_ORDER_ID_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>("CLIENT_ORDER_TAG_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_ORDER_COMMENT_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_TRADE_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_TRADE_ID_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>("CLIENT_TRADE_TAG_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_TRADE_COMMENT_INVALID");
    round_trip::<models::TransactionRejectReason>("ORDER_FILL_POSITION_ACTION_MISSING");
    round_trip::<models::TransactionRejectReason>("ORDER_FILL_POSITION_ACTION_INVALID");
    round_trip::<models::TransactionRejectReason>("TRIGGER_CONDITION_MISSING");
    round_trip::<models::TransactionRejectReason>("TRIGGER_CONDITION_INVALID");
    round_trip::<models::TransactionRejectReason>("ORDER_PARTIAL_FILL_OPTION_MISSING");
    round_trip::<models::TransactionRejectReason>("ORDER_PARTIAL_FILL_OPTION_INVALID");
    round_trip::<models::TransactionRejectReason>("INVALID_REISSUE_IMMEDIATE_PARTIAL_FILL");
    round_trip::<models::TransactionRejectReason>(
        "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "ORDERS_ON_FILL_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ORDER_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>(
        "TAKE_PROFIT_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD",
    );
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_PRICE_MISSING");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_PRICE_INVALID");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_PRICE_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_MISSING");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_TIME_IN_FORCE_INVALID");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_MISSING");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_CLIENT_ORDER_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_CLIENT_ORDER_TAG_INVALID");
    round_trip::<models::TransactionRejectReason>(
        "TAKE_PROFIT_ON_FILL_CLIENT_ORDER_COMMENT_INVALID",
    );
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_MISSING");
    round_trip::<models::TransactionRejectReason>("TAKE_PROFIT_ON_FILL_TRIGGER_CONDITION_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_GUARANTEED_REQUIRED");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_GUARANTEED_PRICE_WITHIN_SPREAD");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_GUARANTEED_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_GUARANTEED_HALTED_CREATE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_GUARANTEED_HALTED_TIGHTEN_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_GUARANTEED_HEDGING_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_GUARANTEED_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_NOT_CANCELABLE");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ORDER_NOT_REPLACEABLE");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_GUARANTEED_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_GUARANTEED_REQUIRED");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_PRICE_MISSING");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_PRICE_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ON_FILL_GUARANTEED_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ON_FILL_GUARANTEED_LEVEL_RESTRICTION_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_DISTANCE_INVALID");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED");
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED",
    );
    round_trip::<models::TransactionRejectReason>(
        "STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING",
    );
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING");
    round_trip::<models::TransactionRejectReason>("STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_REQUIRED");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_PRICE_WITHIN_SPREAD");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_HALTED_CREATE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_CREATE_VIOLATION");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_HALTED_TIGHTEN_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_TIGHTEN_VIOLATION");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_HEDGING_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_NOT_CANCELABLE");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_CANCELABLE",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ORDER_NOT_REPLACEABLE");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_HALTED_NOT_REPLACEABLE",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_VOLUME_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_SPECIFIED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_PRICE_AND_DISTANCE_BOTH_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED_FOR_PENDING_ORDER",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ON_FILL_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ON_FILL_REQUIRED");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ON_FILL_PRICE_MISSING");
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ON_FILL_PRICE_INVALID");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_PRECISION_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_MINIMUM_DISTANCE_NOT_MET",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_VOLUME_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_LEVEL_RESTRICTION_PRICE_RANGE_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>("GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_INVALID");
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_DISTANCE_PRECISION_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_SPECIFIED",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_PRICE_AND_DISTANCE_BOTH_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "GUARANTEED_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID",
    );
    round_trip::<models::TransactionRejectReason>("TRAILING_STOP_LOSS_ORDER_ALREADY_EXISTS");
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ORDER_WOULD_VIOLATE_FIFO_VIOLATION_SAFEGUARD",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_MUTUALLY_EXCLUSIVE_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ORDER_RMO_MUTUAL_EXCLUSIVITY_GSLO_EXCLUDES_OTHERS_VIOLATION",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_PRECISION_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MAXIMUM_EXCEEDED",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_PRICE_DISTANCE_MINIMUM_NOT_MET",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_TIME_IN_FORCE_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_GTD_TIMESTAMP_IN_PAST",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_ID_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_TAG_INVALID",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_CLIENT_ORDER_COMMENT_INVALID",
    );
    round_trip::<models::TransactionRejectReason>("TRAILING_STOP_LOSS_ORDERS_NOT_SUPPORTED");
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_MISSING",
    );
    round_trip::<models::TransactionRejectReason>(
        "TRAILING_STOP_LOSS_ON_FILL_TRIGGER_CONDITION_INVALID",
    );
    round_trip::<models::TransactionRejectReason>("CLOSE_TRADE_TYPE_MISSING");
    round_trip::<models::TransactionRejectReason>("CLOSE_TRADE_PARTIAL_UNITS_MISSING");
    round_trip::<models::TransactionRejectReason>("CLOSE_TRADE_UNITS_EXCEED_TRADE_SIZE");
    round_trip::<models::TransactionRejectReason>("CLOSEOUT_POSITION_DOESNT_EXIST");
    round_trip::<models::TransactionRejectReason>("CLOSEOUT_POSITION_INCOMPLETE_SPECIFICATION");
    round_trip::<models::TransactionRejectReason>("CLOSEOUT_POSITION_UNITS_EXCEED_POSITION_SIZE");
    round_trip::<models::TransactionRejectReason>("CLOSEOUT_POSITION_REJECT");
    round_trip::<models::TransactionRejectReason>("CLOSEOUT_POSITION_PARTIAL_UNITS_MISSING");
    round_trip::<models::TransactionRejectReason>("MARKUP_GROUP_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("POSITION_AGGREGATION_MODE_INVALID");
    round_trip::<models::TransactionRejectReason>("ADMIN_CONFIGURE_DATA_MISSING");
    round_trip::<models::TransactionRejectReason>("MARGIN_RATE_INVALID");
    round_trip::<models::TransactionRejectReason>("MARGIN_RATE_WOULD_TRIGGER_CLOSEOUT");
    round_trip::<models::TransactionRejectReason>("ALIAS_INVALID");
    round_trip::<models::TransactionRejectReason>("CLIENT_CONFIGURE_DATA_MISSING");
    round_trip::<models::TransactionRejectReason>("MARGIN_RATE_WOULD_TRIGGER_MARGIN_CALL");
    round_trip::<models::TransactionRejectReason>("AMOUNT_INVALID");
    round_trip::<models::TransactionRejectReason>("INSUFFICIENT_FUNDS");
    round_trip::<models::TransactionRejectReason>("AMOUNT_MISSING");
    round_trip::<models::TransactionRejectReason>("FUNDING_REASON_MISSING");
    round_trip::<models::TransactionRejectReason>("OCA_ORDER_IDS_STOP_LOSS_NOT_ALLOWED");
    round_trip::<models::TransactionRejectReason>("CLIENT_EXTENSIONS_DATA_MISSING");
    round_trip::<models::TransactionRejectReason>("REPLACING_ORDER_INVALID");
    round_trip::<models::TransactionRejectReason>("REPLACING_TRADE_ID_INVALID");
    round_trip::<models::TransactionRejectReason>("ORDER_CANCEL_WOULD_TRIGGER_CLOSEOUT");
    round_trip::<models::TransactionFilter>("ORDER");
    round_trip::<models::TransactionFilter>("FUNDING");
    round_trip::<models::TransactionFilter>("ADMIN");
    round_trip::<models::TransactionFilter>("CREATE");
    round_trip::<models::TransactionFilter>("CLOSE");
    round_trip::<models::TransactionFilter>("REOPEN");
    round_trip::<models::TransactionFilter>("CLIENT_CONFIGURE");
    round_trip::<models::TransactionFilter>("CLIENT_CONFIGURE_REJECT");
    round_trip::<models::TransactionFilter>("TRANSFER_FUNDS");
    round_trip::<models::TransactionFilter>("TRANSFER_FUNDS_REJECT");
    round_trip::<models::TransactionFilter>("MARKET_ORDER");
    round_trip::<models::TransactionFilter>("MARKET_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("LIMIT_ORDER");
    round_trip::<models::TransactionFilter>("LIMIT_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("STOP_ORDER");
    round_trip::<models::TransactionFilter>("STOP_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("MARKET_IF_TOUCHED_ORDER");
    round_trip::<models::TransactionFilter>("MARKET_IF_TOUCHED_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("TAKE_PROFIT_ORDER");
    round_trip::<models::TransactionFilter>("TAKE_PROFIT_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("STOP_LOSS_ORDER");
    round_trip::<models::TransactionFilter>("STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("GUARANTEED_STOP_LOSS_ORDER");
    round_trip::<models::TransactionFilter>("GUARANTEED_STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("TRAILING_STOP_LOSS_ORDER");
    round_trip::<models::TransactionFilter>("TRAILING_STOP_LOSS_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("ONE_CANCELS_ALL_ORDER");
    round_trip::<models::TransactionFilter>("ONE_CANCELS_ALL_ORDER_REJECT");
    round_trip::<models::TransactionFilter>("ONE_CANCELS_ALL_ORDER_TRIGGERED");
    round_trip::<models::TransactionFilter>("ORDER_FILL");
    round_trip::<models::TransactionFilter>("ORDER_CANCEL");
    round_trip::<models::TransactionFilter>("ORDER_CANCEL_REJECT");
    round_trip::<models::TransactionFilter>("ORDER_CLIENT_EXTENSIONS_MODIFY");
    round_trip::<models::TransactionFilter>("ORDER_CLIENT_EXTENSIONS_MODIFY_REJECT");
    round_trip::<models::TransactionFilter>("TRADE_CLIENT_EXTENSIONS_MODIFY");
    round_trip::<models::TransactionFilter>("TRADE_CLIENT_EXTENSIONS_MODIFY_REJECT");
    round_trip::<models::TransactionFilter>("MARGIN_CALL_ENTER");
    round_trip::<models::TransactionFilter>("MARGIN_CALL_EXTEND");
    round_trip::<models::TransactionFilter>("MARGIN_CALL_EXIT");
    round_trip::<models::TransactionFilter>("DELAYED_TRADE_CLOSURE");
    round_trip::<models::TransactionFilter>("DAILY_FINANCING");
    round_trip::<models::TransactionFilter>("RESET_RESETTABLE_PL");
    round_trip::<models::PriceStatus>("tradeable");
    round_trip::<models::PriceStatus>("non-tradeable");
    round_trip::<models::PriceStatus>("invalid");
    round_trip::<models::InstrumentType>("CURRENCY");
    round_trip::<models::InstrumentType>("CFD");
    round_trip::<models::InstrumentType>("METAL");
    round_trip::<models::DayOfWeek>("SUNDAY");
    round_trip::<models::DayOfWeek>("MONDAY");
    round_trip::<models::DayOfWeek>("TUESDAY");
    round_trip::<models::DayOfWeek>("WEDNESDAY");
    round_trip::<models::DayOfWeek>("THURSDAY");
    round_trip::<models::DayOfWeek>("FRIDAY");
    round_trip::<models::DayOfWeek>("SATURDAY");
    round_trip::<models::AcceptDatetimeFormat>("UNIX");
    round_trip::<models::AcceptDatetimeFormat>("RFC3339");
    round_trip::<models::GuaranteedStopLossOrderModeForInstrument>("DISABLED");
    round_trip::<models::GuaranteedStopLossOrderModeForInstrument>("ALLOWED");
    round_trip::<models::GuaranteedStopLossOrderModeForInstrument>("REQUIRED");
    round_trip::<models::Direction>("LONG");
    round_trip::<models::Direction>("SHORT");
}
